### ISSUE TITLE
lambda argument removal clobbers arguments within lambda

### ISSUE THREAD

**Issue by fastjames** [avo-hq/avo_upgrade#3]
https://github.com/avo-hq/avo_upgrade/blob/53537b1b66c5e6da790e6fe5098299a4872ff909/lib/avo_upgrade/upgrade29to30.rb#L39

Given the following field option:

```
field :budget_total,
  format_using: ->(value) { view_context.number_to_currency(value) }
```

The upgrade script will transform it to
```
field :budget_total,
  format_using: -> { view_context.number_to_currency }
```

The transformed code is invalid, as the value does need to be provided to `number_to_currency`.

**Comment by adrianthedev** [comment]
I think the `value` is available in that block. We pass it behind the scenes. This is our push to make all APIs more consistent and not have any arguments in our blocks.

Try to use it regularly:

`format_using: -> { view_context.number_to_currency(value) }`

**Comment by fastjames** [comment]
> I think the `value` is available in that block. We pass it behind the scenes. This is our push to make all APIs more consistent and not have any arguments in our blocks.
> 
> Try to use it regularly:
> 
> `format_using: -> { view_context.number_to_currency(value) }`

I think my issue description may have been unclear -- the upgrade script currently strips both occurrences of `(value)` from the line of code, where it should only remove the first occurence that is the lambda param. I agree that the second occurrence (the param being passed to number_to_currency) should remain in the code.

**Comment by adrianthedev** [comment]
pfff. I misunderstood it! got it now! Thanks for writing back!
